// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package querytest

import (
	"encoding/json"

	"github.com/averche/pqtype"
)

type Foo struct {
	A json.RawMessage
	B json.RawMessage
	C pqtype.NullRawMessage
	D pqtype.NullRawMessage
}
